Lab2
Mashalets/lets-go pull request #2
Opened 2024-10-11 17:34 UTC by Mashalets

2024-10-24 15:43 UTC, lamer0k requested changes
Есть над чем подумать

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +image::Типы данных в С++.png[]
картинка не показывается

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +|Тип | Длина |Комментарий
Длина разве всегда такая? Какое правило границ длины типов для языка С++? А эти длины для какой платформы?

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +|Тип | Длина |Комментарий
Тоже самое, это частный случай для какой платформы?

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +Смешивание типов данных может привести к ошибкам, непредсказуемым результатам и снижению производительности. Разные типы обрабатываются по-разному, и без явного приведения типов программа не всегда с
Пример надо, как производительность может снизиться  к примеру?

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +.Псевдонимы
Надо тогда уже все привести, почему только эти то?

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +* int() - преобразует данные в целое число.
Это откуда? У нас же С++

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +*ptr = 42; // Изменение значения в этой ячейке памяти
Как называется операция *ptr

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +std::uint32_t* ptr = reinterpret_cast<std::uin32_t>(1);
[source, cpp]
----

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +Таким образом, b будет равно 10, при условии, что доступ к памяти по адресу 1 разрешен и действительно содержит значение 10.
Нет - не будет 10.

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +Разыменование: auto b = *ptr; приводит к тому, что b будет равно значению, находящемуся по адресу 1.
Какое число то?

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +В данном случае b будет равно 10, при условии, что доступ к памяти по адресу 1 разрешён.
Нет

2024-10-24 15:43 UTC, lamer0k commented on lab2.adoc
> +Переменная b будет иметь тип const char.
нет

2024-11-24 14:19 UTC, lamer0k requested changes
1. Не все поправила
2. Надо слить Лабу 1 и удалить её ветку.

2024-11-28 11:50 UTC, Mashalets commented on lab2.adoc
> +image::Типы данных в С++.png[]
Поправила

2024-11-28 11:50 UTC, Mashalets commented on lab2.adoc
> +|Тип | Длина |Комментарий
Поправила

2024-11-28 11:50 UTC, Mashalets commented on lab2.adoc
> +|Тип | Длина |Комментарий
Поправила

2024-11-28 11:50 UTC, Mashalets commented on lab2.adoc
> +Смешивание типов данных может привести к ошибкам, непредсказуемым результатам и снижению производительности. Разные типы обрабатываются по-разному, и без явного приведения типов программа не всегда с
Поправила

2024-11-28 11:50 UTC, Mashalets commented on lab2.adoc
> +* int() - преобразует данные в целое число.
Поправила

2024-11-28 11:50 UTC, Mashalets commented on lab2.adoc
> +*ptr = 42; // Изменение значения в этой ячейке памяти
Поправила

2024-11-28 11:50 UTC, Mashalets commented on lab2.adoc
> +std::uint32_t* ptr = reinterpret_cast<std::uin32_t>(1);
Поправила

2024-11-28 11:50 UTC, Mashalets commented on lab2.adoc
> +Таким образом, b будет равно 10, при условии, что доступ к памяти по адресу 1 разрешен и действительно содержит значение 10.
Поправила

2024-11-28 11:51 UTC, Mashalets commented on lab2.adoc
> +Разыменование: auto b = *ptr; приводит к тому, что b будет равно значению, находящемуся по адресу 1.
Поправила

2024-11-28 11:51 UTC, Mashalets commented on lab2.adoc
> +В данном случае b будет равно 10, при условии, что доступ к памяти по адресу 1 разрешён.
Поправила

2024-11-28 11:51 UTC, Mashalets commented on lab2.adoc
> +Переменная b будет иметь тип const char.
Поправила

2024-11-29 11:16 UTC, lamer0k approved these changes

2024-11-30 10:15 UTC, merged