Lab3_4
Mashalets/lets-go pull request #3
Opened 2024-11-14 14:16 UTC by Mashalets

2024-11-24 14:14 UTC, lamer0k requested changes
Надо добавить про single resposibility + исправить ошибки

2024-11-24 14:14 UTC, lamer0k commented on LAB3_4.adoc
> +
Добавить сюда титульник через include::

2024-11-24 14:14 UTC, lamer0k commented on LAB3_4.adoc
> +Порт - это устройство для обмена данными (ввод и вывод). С помощью портов можно управлять работой других устройств. В микроконтроллере есть 5 портов общего назначения, 16 линий ввода/вывода.
Отлично, только про порт мы еще не говорили :)

2024-11-24 14:14 UTC, lamer0k commented on LAB3_4.adoc
> +== Включение светодиодов с помощью указателей
А вот говорили про Single Responsibility принцип во его и надо описать.

2024-11-24 14:14 UTC, lamer0k commented on LAB3_4.adoc
> +         for(auto it: leds)
Все друг у друга списываете и неправильно.

2024-11-24 14:14 UTC, lamer0k commented on LAB3_4.adoc
> +Можно сделать вывод, что использование классов позволяет организовать программу так, чтобы она была более понятной и удобной для редактирования.
Раздел вывод еще.

2024-11-28 13:13 UTC, Mashalets commented on LAB3_4.adoc
> +
Поправила

2024-11-28 13:14 UTC, Mashalets commented on LAB3_4.adoc
> +Порт - это устройство для обмена данными (ввод и вывод). С помощью портов можно управлять работой других устройств. В микроконтроллере есть 5 портов общего назначения, 16 линий ввода/вывода.
Поправила, "удалила" :))

2024-11-28 13:14 UTC, Mashalets commented on LAB3_4.adoc
> +== Включение светодиодов с помощью указателей
Поправила

2024-11-28 13:14 UTC, Mashalets commented on LAB3_4.adoc
> +Можно сделать вывод, что использование классов позволяет организовать программу так, чтобы она была более понятной и удобной для редактирования.
Поправила

2024-11-29 11:18 UTC, lamer0k approved these changes

2024-11-30 10:15 UTC, merged